sudo: required
language: android
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: 19eyMY7VgMo8MWBLGkhbQVjnShl/LzatWV6TDSw8L3ddWLq5jzLAgcbT94fATVW7Usi8pmkqyIXE3VolcL4Up/4NUq3Y5uXqgZGh/PhK0aFAq7wQ1btiU/ZrS4XEcujgWIkBvW2K2nHBkUsMLi2QIAWkPwGxoC2/EI2clVvMJzQIVtmnrEXpKZ1ZdG2pjSq4JjoGnz9MXYQNdUdKTSHqJK8FTtAbqPV9AVmVpjIRnjlSBHDNNwpwIa/XNI8ALhnoXfB6s8YVdw5kSftT94xdE9Zq5zQWZD5+JKzSIabHWENnP+10f7e3/tv4x8DrxKUkim0MPPByawda8s6cZl6eU1M9Vyt0rk1QnQcQA1w9y1ituYcTJoCWTAUqFIukF8eAHswAOAt0p451jN59dKw/4ZhRemg1pUwXG6Hmc7BuVjF2ynMHq9S7HAtU0NMH1Ux1fhQOzFUce/m6XvL8dvG/7RbEYnv0RoOPRhDgao4/27+7uxMKjl119UNO2G+8ZsLPrGQ04rzeNfOiF2vJ1nLO/hDcAle3FzcUw2kahkrbNeQXnAjuArXOsABrxxuvZnfJmb1K64MNEYghKA/sIs+STKDeIax1Ot2m9LygvEBKIaYCnHJjj3PvwaWixIY34994dJMSjXV0cJoT80WX/4Lupd4toNV00aw1B55p9LuWpZQ=
  - secure: SFnWvhJvs/3N/j4f1PXLJ6ytN5I65SMiYLP3K9Ky9GAxQ9B/H8sFbxao6PHeoVWod//K9eQjUuEjHpmZtC8sbF7B4KVPEwYoavdGsG8IvhX3o8W21KY6JngXPoghZ38FqZMLdvDmYD5yG2VWJsSsExup5Wa2WlJr/kITE/dniLga0EP029FSRNLtP57JsvWxkKAhEB1jIAdjyZPBC3XG9cI8aljpgtLWI0Zsu9bHzl2qtv7guD19SnnOUu6poQ2KcZvxprgwtpDNPma1pmIDSBeYQk+04atXClG+7QbOdtVhheYYFjkGGP+X5pUzo9LU30ILygid8rKfF40CwlIGpVsvGPF25UIEtIwg06eSasJJBR4iQ1s+gJA3Wqdw6o7sQa2WErIuDZe9WM/MmhhG7+Ph8G/s3Q4fo2FLuPca/+aQXaqTEAOdRdY2a9mj/iMlpB9WCQFL8Kjejk4KExy5AQia2ulJXZHh9MemzhwwSP1uMZJj3G9BTU9YGxsk0gp2nnhwg9nvpeB+mKwGwko7oN9Vf+/wyrPH9GPbKoPyxH0xrhiPw1Ol6+HEh5Tczg8Mdwwwh/ofM18vOkXgYAlP8h7boWujyDRIKcYFpo7d4pe/1OVNTy9h4HkvEmxmdYRhqrkTvXvRpqJxaYqCgKRxx1FWQa7XuUSbVxx+iooF58c=
  - secure: c8WiT0syUlOOMDIigzy4IkKnjqa8Hgyi2pekNt2m/VYAAT027L6zvsbDLTsL8EWAPfctlmHY+lUPmDn2Y1dovd7wKIKwZXO1EFytfrqBFB+hFeFZDkg5mlRotM/irks/fhjH9WdsOsSC3SLR/NPTkvz7EAYRr3oeyhjDc8X/SVY7hVSlWvwZb2lwCnw+J+hgopTJnCnFn2Ts4XvX4DF6kwLcUfFRqMoqDw2AYIfPAKAQ5pDyLbR1a1C3cdBCKXiZhZ5TMC75HZvRWRkFsmzvbEraxt6lzBMfBCQjzUX+BgzJjFygpwLHSCvlx+xy4Op/E/37Ek9nQrDxf08xW7rmJrvqnDRBdgEfXWOmPixS7By/3YQoePTcgAB7sOlp9BN3jQsf28iH42iNSbPw3EV9Hw3xG5KuU3tWUyBjNZ6REkBsYxINI+Kr3BxDV2Mo48xO85/R59HAJRf1iXwn+sPnf8lkiv9CYRDiRDHwln9zTnCngHPWz30fwZiOFJoeNOZnI0Q9UTQ36+mmekSJwzF/vUnN+7KeoskAHmXsIfIYcKDPAlKZAKhMe6dBnFxoSnU88Xqo/vQHXeOT22CrHHHgR131P0j7Lb17WEhaawYEay7d18J5fMqhaRS5Ef8h/NmScLxk3AKcFTaGJfEGUZ9RXXatCwfVlzJmtRs/V6SIiXE=
android:
  components:
  - tools
  - tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
script:
- "./gradlew clean test build"
before_deploy:
#- openssl aes-256-cbc -K $encrypted_53fbf29b3729_key -iv $encrypted_53fbf29b3729_iv
#  -in keystore.jks.enc -out keystore.jks -d
- cd app/build/outputs/apk/release
#- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/keystore.jks
#  -storepass $storepass -keypass $keypass app-release-unsigned.apk key0
#- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk
  TravisAndroid.apk"
- cd -
- scripts/tag.sh
deploy:
  provider: releases
  on:
    branch: master
  api_key:
    secure: Lb4MkrifEzkRd89Okzr82SPh44xpojz7ZeE43yt/wOJX7ZD0e0wyZ6u5M2pDaMjtoqU2YGMd2ppqyMQtqNEkQA2L1NQEd0G9Ch5n0nt5Dmw2AioOWZbfHW1uC/mX/kwDZrDWwxnq/y2aUlTA52ZSF5z8nfKGWJTu5/SJX0H/d0nmbgOE3HfHx7FrWJ+IkRtTXzuXKAbc9upNp5aTiQ2QU9xoH2H3JZZFbSqhT3v4sMRTVl9iJgY17AM9XFImih5wT3h5p8F1qE5sGZWL5s5CJNoE3HedcJI4h8Y9G+GKnJB7DDRM3CKwQg/d/EZiIVGqLfIValgjVEtb/s5/D3TIbBnGZIsitQMVLia+i7VNyYgURC6/rl9vvaOh1h2O8VGhe3avLbv1NiukHApajTvVWpVxrs7xigMmMADpX/tm77OKXg1KvHKse0hbTPxwACLTYKfWz9Ngr1xONd9GqHegrhR9OCPcKURvwB9s1YDQBmfkkGTQIEsGty9KTfnHsuy0roCv+VY3tygmcUVd3uBsho5Jr2GbUiE4HrVWfgxV0lQZYyLhRJ1OOcYHakIor0VhJqP2A1BWRKgN2RLzb3RcncT3jo3zP7VXto+4oVC/6rhKlFAOBNlIIiaA7iGdHgYB4Yirv4firYUdRT0snPSR8Y9Qp5B7S2TPbhs/AMnHEcc=
  file: app/build/outputs/apk/release/TravisAndroid.apk
  overwrite: true
  skip_cleanup: true