sudo: required
language: android
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: WwJavOO+SEjdWE9O1MGILeLg7OzRy0KtyCDGhZHQIcwkgbw7Ch37WIacTpqXmPb14zkRq1QczJpGv5/2HorN9c/rYDB7S0OlKCVkS/0+/VWzUCFHGMPnnV4ZExJooaE1a0coTyWMesg6Qudtx5QRkPUkm3M+SZeRKBxxOGQIw9d0+ZaO3GYySXPJ09Zn98yo7aQGyqY/z5fzPcTMplofMMaGCVVVlcbIJ1IBIOCKHh20mavmuasOmGLVXCD8Z5ZUfcnsdlf2EZShLOz7PduzF0wWqH3UChctU2DBKQ8PH6tr6hwW3ND6+Oi3/VJbfs8A1jBRbX7SBuFcx/OG7pHrLt6zCIkzDjBk17MRNU+Oz4f9EozGMJxhY0F1HI4pGeomTx4pY7f3iFFkq2ebCcOQtGLpT+dnKiOAXHcJHP5JsRtqoTOCOPJR5KFLQPRi0Yb++q6zQ7+72cus79k15eT3ZIwpVjodD7MRd6BaeMUGTeS9/wa7xLUfK7CfnOwN7ky1TduSEJnhY/IEhOLnIgfqyy033KooP80oHqhTUgjBV0Dtg4b4z4Ev07r5DaywYcQ8XBh4n7WSrDXP3W7IuW0vsb3pDSSJzAstqIzeRis3R76jsy8RCwmcInDqxFb864AO7YUaBLjIBiIpQdXTWc/ZCShR4eABA0tk5rwfMNG/hLc=
  - secure: 23JxM6jeLm7whdQyAYPHI8Njc3aVLijGMm0YwuChW3QTXPGF0nVMgG6sL1f6lYf1kZQpZG8iHJE4DhsC2gRIWukMGhCfF6yl7yhZHWgSU0Uw7LY0pnwgBtFwopkIwQYSxAlHXNwXbBzP5daR5Yl/OKJFLc+a9D8huptMAu3ZpaMW4CQIevcje801126fuGRXwq1THMiLsC6h9gcPlnVw4noEPEfmVxackJT7ja7aHAZcfHwDCQnHUrRnWDcO+pRqOsH909bnhJWOP8PyZ3dhwIcsFDJGRnWgCm+TXt4Cm8me6WgMvFrjb8pTW4JBS5ZHZ694/INgR8AvuBRCQGkB4KCdhaynPhYESFzdDP1CAyRGzHf+PeTninEYib34fqzFiFwSx1SqQO6nx6hTtnqgaTl+9IE7YGEdHu+DFHVtSuysrpuKHoZ6vFF2DthpBn0c8HreejnOUNTx6QA8UDpe/sx5Zt7mSDl2mYhkJ1MBwOZLi0LhzUEp5QuQEiP0y/WH6D8qH4hvqEHh0MXZYsvgZHCeCLA67JOduH1i7cJ11IgAc//UIzbF7nm+xj/xG+hPN3hDQ9TWUEuBnFzNUoA2i0xNSICPet0Smp5s+1C+TJhlqgYfTxOtVo670ELBLrwI+IEvfWtMm2yS+2gV5Smy0zD15r33ajcIK4XW1XQuZPU=
  - secure: D4wbF7Jx2LtZp1Hct3R51f2vOfUPp/HtHC2ZnQbiG19WjxrLvRP+uS+OAif9jiPGUxt29Bp1vbMOXi7O7fGk5JeAbazjz2wUK7Yj0BzGN3KMGL1Uw3vT75DmVRq4bjB1OE8+OjZca3F1/BQIdXF55VLv6WDnVHW7T50Nemu4NgJvjVKgEC2tqeexvBB7I4DX0adteyNMCcqL7iqqret3crHvHigaPHXu4SHGerXtfW6yHEJ/6zf+brQAsQSwxSc/s9OHOzMRiG7vguj6vXUTEiHxJJV4LTrmVPxY6eXzhg+XDLixXItoprI1FAnzHHOLdAwW3UIBjBhfWupyUY6zqzXDoMAEFfJBRoZD8gKdaoNzwPyg6MjKFHLMNYyygfqvrbJhtKBioja11CPAxP31CAOJ17gru5s+pjRXEAkPqnlAeLzLbGSuQFrsrB/JCwFdf5iPPlpj0j+CFCkmEw4f5cMANjmmDq91V8MMbyPkLJep04YqfjQJ8qmWD7Sqx4jhvIN1NBkWtq+aIoWQzhlxXD5QU8YfmroZOhMWxa6eszF9CfZ2XdaRr8OpJldeO4WR6EnH5MdqLwfZPEjEUIGzMJ8Q9RhRva2oQHZ5oFHrTRjIzb8u+CeKV28LTGqYbJpb6oTFScuNyIG8+PtNmHODNU7xI+mY1gWl0uGOySIDF2o=
android:
  components:
  - tools
  - tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
script:
- "./gradlew clean test build"
before_deploy:
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/keystore.jks
  -storepass horizon -keypass horizon app-release-unsigned.apk key0
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk
  TravisAndroid.apk"
- cd -
- scripts/tag.sh
deploy:
  provider: releases
  on:
    branch: master
  api_key:
    secure: Lb4MkrifEzkRd89Okzr82SPh44xpojz7ZeE43yt/wOJX7ZD0e0wyZ6u5M2pDaMjtoqU2YGMd2ppqyMQtqNEkQA2L1NQEd0G9Ch5n0nt5Dmw2AioOWZbfHW1uC/mX/kwDZrDWwxnq/y2aUlTA52ZSF5z8nfKGWJTu5/SJX0H/d0nmbgOE3HfHx7FrWJ+IkRtTXzuXKAbc9upNp5aTiQ2QU9xoH2H3JZZFbSqhT3v4sMRTVl9iJgY17AM9XFImih5wT3h5p8F1qE5sGZWL5s5CJNoE3HedcJI4h8Y9G+GKnJB7DDRM3CKwQg/d/EZiIVGqLfIValgjVEtb/s5/D3TIbBnGZIsitQMVLia+i7VNyYgURC6/rl9vvaOh1h2O8VGhe3avLbv1NiukHApajTvVWpVxrs7xigMmMADpX/tm77OKXg1KvHKse0hbTPxwACLTYKfWz9Ngr1xONd9GqHegrhR9OCPcKURvwB9s1YDQBmfkkGTQIEsGty9KTfnHsuy0roCv+VY3tygmcUVd3uBsho5Jr2GbUiE4HrVWfgxV0lQZYyLhRJ1OOcYHakIor0VhJqP2A1BWRKgN2RLzb3RcncT3jo3zP7VXto+4oVC/6rhKlFAOBNlIIiaA7iGdHgYB4Yirv4firYUdRT0snPSR8Y9Qp5B7S2TPbhs/AMnHEcc=
  file: app/build/outputs/apk/release/TravisAndroid.apk
  overwrite: true
  skip_cleanup: true